service: attendance-server
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:ap-northeast-1:*:*'

functions:
  login:
    handler: src/functions/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true
  logout:
    handler: src/functions/logout.handler
    events:
      - http:
          path: logout
          method: delete
          cors: true
  getWorkTable:
    handler: src/functions/getWorkTable.handler
    events:
      - http:
          path: work-table
          method: get
          cors: true

# https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
resources:
  Resources:
    UserDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'user'
    WorkTableDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: year_month_day
            AttributeType: S
          - AttributeName: year_month
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
          - AttributeName: year_month_day
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: 'gsi_email_year_month'
            KeySchema:
              - AttributeName: 'email'
                KeyType: 'HASH'
              - AttributeName: 'year_month'
                KeyType: 'RANGE'
            # GSIで検索した時に取得する属性を指定している
            Projection:
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: '1'
              WriteCapacityUnits: '1'
        TableName: 'work_table'
