service: attendance-server
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:ap-northeast-1:*:*'

plugins:
  - serverless-plugin-additional-stacks

custom:
  # https://github.com/serverless/serverless/issues/3183
  # https://github.com/nordcloud/serverless-plugin-additional-stacks
  additionalStacks:
    permanent:
      Resources:
        # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
        UserDynamoDbTable:
          Type: 'AWS::DynamoDB::Table'
          #DeletionPolicy: Retain
          Properties:
            AttributeDefinitions:
              - AttributeName: email
                AttributeType: S
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
            TableName: 'user'
        WorkTableDynamoDbTable:
          Type: 'AWS::DynamoDB::Table'
          #DeletionPolicy: Retain
          Properties:
            AttributeDefinitions:
              - AttributeName: email
                AttributeType: S
              - AttributeName: year_month_day
                AttributeType: S
              - AttributeName: year_month
                AttributeType: S
            KeySchema:
              - AttributeName: email
                KeyType: HASH
              - AttributeName: year_month_day
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
            GlobalSecondaryIndexes:
              - IndexName: 'gsi_email_year_month'
                KeySchema:
                  - AttributeName: 'email'
                    KeyType: 'HASH'
                  - AttributeName: 'year_month'
                    KeyType: 'RANGE'
                # GSIで検索した時に取得する属性を指定している
                Projection:
                  ProjectionType: 'ALL'
                ProvisionedThroughput:
                  ReadCapacityUnits: '1'
                  WriteCapacityUnits: '1'
            TableName: 'work_table'

functions:
  login:
    handler: src/functions/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true
  logout:
    handler: src/functions/logout.handler
    events:
      - http:
          path: logout
          method: delete
          cors: true
  getWorkTable:
    handler: src/functions/getWorkTable.handler
    events:
      - http:
          path: work-table
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                email: true
                year: true
                month: true
              #headers:
              #  Authorization: true
  putWorkTable:
    handler: src/functions/putWorkTable.handler
    events:
      - http:
          path: work-table
          method: put
          cors: true
  putUser:
    handler: src/functions/putUser.handler
    events:
      - http:
          path: user
          method: put
          cors: true
  deleteUser:
    handler: src/functions/deleteUser.handler
    events:
      - http:
          path: user
          method: delete
          cors: true
